version: "3"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nextjs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
